insert into job_roles (professional_area_id, name, description, min_salary, max_salary, currency) values
  ((select id from professional_areas where name = 'Tecnología'), 'Desarrollador Frontend', 'Construye interfaces web y aplicaciones cliente.', 18000, 40000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Desarrollador Backend', 'Construye APIs, servicios y lógica de servidor.', 20000, 45000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Desarrollador Full Stack', 'Domina tanto el frontend como el backend de las aplicaciones.', 25000, 55000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Desarrollador Móvil', 'Crea aplicaciones nativas o multiplataforma para iOS y Android.', 22000, 50000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Arquitecto de Software', 'Diseña la estructura de alto nivel y los patrones de sistemas de software.', 45000, 80000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Arquitecto Cloud', 'Diseña y gestiona infraestructuras en plataformas en la nube (AWS, Azure, GCP).', 50000, 90000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Ingeniero DevOps', 'Automatiza despliegues, integración continua y administra infraestructura.', 30000, 65000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Site Reliability Engineer (SRE)', 'Garantiza la disponibilidad, latencia y rendimiento de servicios a gran escala.', 35000, 70000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Ingeniero de Datos (Data Engineer)', 'Diseña y mantiene arquitecturas de procesamiento y bases de datos grandes.', 30000, 60000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Científico de Datos (Data Scientist)', 'Analiza datos complejos y crea modelos predictivos.', 35000, 70000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Analista de Datos', 'Interpreta datos para generar reportes e insights de negocio.', 18000, 38000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Machine Learning Engineer', 'Desarrolla modelos de inteligencia artificial y los pone en producción.', 40000, 80000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Administrador de Bases de Datos (DBA)', 'Configura, mantiene y asegura el rendimiento de bases de datos.', 25000, 50000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Ingeniero de Ciberseguridad', 'Protege redes, sistemas y programas de ataques digitales.', 35000, 75000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Pentester / Ethical Hacker', 'Realiza pruebas de penetración para encontrar vulnerabilidades.', 30000, 70000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'QA Automation Engineer', 'Desarrolla scripts y frameworks para pruebas automáticas de software.', 22000, 48000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'QA Manual Tester', 'Realiza pruebas funcionales, exploratorias y de regresión manuales.', 15000, 30000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Administrador de Sistemas (SysAdmin)', 'Mantiene sistemas informáticos y redes de servidores operando correctamente.', 20000, 40000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Ingeniero de Redes', 'Diseña, implementa y mantiene redes de telecomunicaciones y datos.', 22000, 45000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Scrum Master', 'Facilita metodologías ágiles en equipos de desarrollo.', 25000, 50000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Product Manager (Técnico)', 'Lidera la estrategia y desarrollo de productos tecnológicos.', 35000, 75000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Tech Lead / Líder Técnico', 'Lidera técnicamente al equipo de desarrollo y toma decisiones de arquitectura.', 45000, 85000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Ingeniero de Sistemas Embebidos', 'Desarrolla software para hardware específico o dispositivos IoT.', 25000, 55000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Desarrollador de Videojuegos', 'Crea motores, mecánicas y lógicas para juegos interactivos.', 20000, 50000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Ingeniero Web3 / Blockchain', 'Desarrolla contratos inteligentes y aplicaciones descentralizadas (dApps).', 40000, 90000, 'MXN'),
  ((select id from professional_areas where name = 'Tecnología'), 'Especialista en Soporte TI', 'Resuelve incidencias técnicas de hardware y software a usuarios finales.', 12000, 25000, 'MXN')
on conflict (professional_area_id, name) do nothing;
